TARGET:= libproxy_malloc.so

C_SOURCES:= $(wildcard ../common/*.c)

ROOTDIR:= ../
SRCDIR:= ./
OBJDIR:= .objs/build/
OUTDIR:= $(ROOTDIR)
HEADERS:=

CFLAGS:= -I../common
CXXFLAGS:=
LDFLAGS:= -ldl

include ../build_so.mak
